GRANT CONNECT ON DATABASE revolution TO runtime, migration, ingest, backup;
GRANT USAGE ON SCHEMA public TO runtime, ingest, backup;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO runtime;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE knowledge_documents, knowledge_chunks
  TO ingest;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO backup;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO backup;

ALTER ROLE migration NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
